# Generated by Django 6.1.1 on 2026-09-14 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basepage", "0003_finalize_page_model"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="basepage",
            name="canonical_url",
            field=models.URLField(blank=True, help_text="Optional canonical URL override."),
        ),
        migrations.AddField(
            model_name="basepage",
            name="robots_noindex",
            field=models.BooleanField(default=False, help_text="Ask search engines not to index this page."),
        ),
        migrations.AddField(
            model_name="basepage",
            name="social_image",
            field=models.ForeignKey(blank=True, help_text="Image used when this page is shared on social media.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="wagtailimages.image"),
        ),
    ]
