# Generated by Django 6.1.1 on 2026-10-04 12:28

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basepage', '0004_basepage_canonical_url_basepage_robots_noindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('body', wagtail.fields.StreamField([('heading', 3), ('richtext', 4), ('content_image', 7), ('note', 13), ('card', 17), ('card_grid', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'Heading 2'), ('h3', 'Heading 3'), ('h4', 'Heading 4'), ('h5', 'Heading 5'), ('h6', 'Heading 6')], 'help_text': 'Choose the heading level that fits the page structure.'}), 2: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'label': 'Visually hide heading', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1), ('visually_hidden', 2)]], {}), 4: ('blocks.content.RichTextBlock', (), {}), 5: ('wagtail.images.blocks.ImageBlock', [], {}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {}), 9: ('wagtail.blocks.CharBlock', (), {'label': 'Link text', 'max_length': 100, 'required': False}), 10: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Internal page', 'required': False}), 11: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('text', 9), ('page', 10), ('url', 11)]], {'label': 'Link', 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('link', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': True}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('text', 9), ('page', 10), ('url', 11)]], {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 5), ('title', 14), ('content', 15), ('link', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional URL anchor. Leave blank to generate one from the heading.', 'required': False}), 20: ('blocks.content.RichTextBlock', (), {'required': False}), 21: ('wagtail.blocks.ListBlock', (17,), {'min_num': 1}), 22: ('wagtail.blocks.StructBlock', [[('heading', 18), ('anchor', 19), ('visually_hide_heading', 2), ('introduction', 20), ('cards', 21)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('basepage.basepage',),
        ),
    ]
